### ISSUE TITLE
Unable to install on Windows

### ISSUE THREAD

**Issue by claycephas** [q-nick/npm-gui#1]
I get errors trying to install on Windows 7 64 bit.

    npm install -g npm-gui

Results from npm-debug.log

```
> utf-8-validate@1.1.0 install C:\Users\canders2\AppData\Roaming\npm\node_modules\npm-gui\node_modul
es\angular-websocket\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild


C:\Users\canders2\AppData\Roaming\npm\node_modules\npm-gui\node_modules\angular-websocket\node_modul
es\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Users\canders2\AppDat
a\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuil
d )  else (node  rebuild )
gyp: C:\Users\canders2\.node-gyp\4.1.1\common.gypi not found (cwd: C:\Users\canders2\AppData\Roaming
\npm\node_modules\npm-gui\node_modules\angular-websocket\node_modules\ws\node_modules\utf-8-validate
) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\canders2\AppData\Roaming\npm\node_modules\npm\
node_modules\node-gyp\lib\configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\canders2\\AppData\\Roaming\\npm\\
node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\canders2\AppData\Roaming\npm\node_modules\npm-gui\node_modules\angular-websock
et\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok

> bufferutil@1.1.0 install C:\Users\canders2\AppData\Roaming\npm\node_modules\npm-gui\node_modules\a
ngular-websocket\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild


C:\Users\canders2\AppData\Roaming\npm\node_modules\npm-gui\node_modules\angular-websocket\node_modul
es\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\canders2\AppData\Ro
aming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
 else (node  rebuild )
gyp: C:\Users\canders2\.node-gyp\4.1.1\common.gypi not found (cwd: C:\Users\canders2\AppData\Roaming
\npm\node_modules\npm-gui\node_modules\angular-websocket\node_modules\ws\node_modules\bufferutil) wh
ile reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\canders2\AppData\Roaming\npm\node_modules\npm\
node_modules\node-gyp\lib\configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\canders2\\AppData\\Roaming\\npm\\
node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\canders2\AppData\Roaming\npm\node_modules\npm-gui\node_modules\angular-websock
et\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0

> bufferutil@1.2.1 install C:\Users\canders2\AppData\Roaming\npm\node_modules\npm-gui\node_modules\w
s\node_modules\bufferutil
> node-gyp rebuild


C:\Users\canders2\AppData\Roaming\npm\node_modules\npm-gui\node_modules\ws\node_modules\bufferutil>i
f not defined npm_config_node_gyp (node "C:\Users\canders2\AppData\Roaming\npm\node_modules\npm\bin\
node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp: C:\Users\canders2\.node-gyp\4.1.1\common.gypi not found (cwd: C:\Users\canders2\AppData\Roaming
\npm\node_modules\npm-gui\node_modules\ws\node_modules\bufferutil) while reading includes of binding
.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\canders2\AppData\Roaming\npm\node_modules\npm\
node_modules\node-gyp\lib\configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\canders2\\AppData\\Roaming\\npm\\
node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\canders2\AppData\Roaming\npm\node_modules\npm-gui\node_modules\ws\node_modules
\bufferutil
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.1.0
npm WARN optional dep failed, continuing fsevents@1.0.7

> utf-8-validate@1.2.1 install C:\Users\canders2\AppData\Roaming\npm\node_modules\npm-gui\node_modul
es\ws\node_modules\utf-8-validate
> node-gyp rebuild


C:\Users\canders2\AppData\Roaming\npm\node_modules\npm-gui\node_modules\ws\node_modules\utf-8-valida
te>if not defined npm_config_node_gyp (node "C:\Users\canders2\AppData\Roaming\npm\node_modules\npm\
bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp: C:\Users\canders2\.node-gyp\4.1.1\common.gypi not found (cwd: C:\Users\canders2\AppData\Roaming
\npm\node_modules\npm-gui\node_modules\ws\node_modules\utf-8-validate) while reading includes of bin
ding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\canders2\AppData\Roaming\npm\node_modules\npm\
node_modules\node-gyp\lib\configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\canders2\\AppData\\Roaming\\npm\\
node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\canders2\AppData\Roaming\npm\node_modules\npm-gui\node_modules\ws\node_modules
\utf-8-validate
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.2.1
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
C:\Users\canders2\AppData\Roaming\npm\npm-gui -> C:\Users\canders2\AppData\Roaming\npm\node_modules\
npm-gui\bin\npm-gui

> npm-gui@0.1.4 install C:\Users\canders2\AppData\Roaming\npm\node_modules\npm-gui
> npm run browserify:js


> npm-gui@0.1.4 browserify:js C:\Users\canders2\AppData\Roaming\npm\node_modules\npm-gui
> ./node_modules/browserify/bin/cmd.js ./lib/public/app/vendor.js -o ./lib/public/bundle.js

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\canders2\\AppData\\Roaming\\npm\\nod
e_modules\\npm\\bin\\npm-cli.js" "run" "browserify:js"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.1
npm ERR! code ELIFECYCLE
npm ERR! npm-gui@0.1.4 browserify:js: `./node_modules/browserify/bin/cmd.js ./lib/public/app/vendor.
js -o ./lib/public/bundle.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the npm-gui@0.1.4 browserify:js script './node_modules/browserify/bin/cmd.js ./li
b/public/app/vendor.js -o ./lib/public/bundle.js'.
npm ERR! This is most likely a problem with the npm-gui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/browserify/bin/cmd.js ./lib/public/app/vendor.js -o ./lib/public/bundle.
js
npm ERR! You can get their info via:
npm ERR!     npm owner ls npm-gui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\canders2\AppData\Roaming\npm\node_modules\npm-gui\npm-debug.log
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\canders2\\AppData\\Roaming\\npm\\nod
e_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm-gui"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.1
npm ERR! code ELIFECYCLE

npm ERR! npm-gui@0.1.4 install: `npm run browserify:js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the npm-gui@0.1.4 install script 'npm run browserify:js'.
npm ERR! This is most likely a problem with the npm-gui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run browserify:js
npm ERR! You can get their info via:
npm ERR!     npm owner ls npm-gui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\canders2\npm-debug.log

```

**Comment by q-nick** [comment]
It's not really bug. Only optional dependencies failed in "ws" package. Everything should work properly. Little bugifx has been added in version 0.1.5 for browserify error.

"ws" dependencie will be removed in future versions.

**Comment by q-nick** [comment]
version 0.1.6 should fix all errors

**Comment by claycephas** [comment]
Great. I'm able to install now. However, now when I run `npm-gui` I get the following in the console:

    npm-gui panel running at http://0.0.0.0:1337/
    
    I will be waiting here to help you with your work with pleasure.

And this is what I see in the browser navigating to `http://localhost:1337`:

    GET http://localhost:1337/ 404 (Not Found)

**Comment by q-nick** [comment]
That`s true, Thanks for feedback. Probably it`s problem with paths which are linux-like not for windows.

**Comment by q-nick** [comment]
That was yet another problem on Windows. Now global installation on it should work properly (v0.1.8).

**Comment by claycephas** [comment]
I'm in. Thanks!
