### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by clabough** [q-nick/npm-gui#17]
I get this after clicking to perform some updates

> I will be waiting here to help you with your work with pleasure.
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Object.c [as JSONparse] (C:\Users\Shawn\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:19:793)
    at C:\Users\Shawn\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:206:3358
    at i (C:\Users\Shawn\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:1:888)
    at i._settlePromiseFromHandler (C:\Users\Shawn\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:207:19369)
    at i._settlePromise (C:\Users\Shawn\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:207:20172)
    at i._settlePromise0 (C:\Users\Shawn\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:207:20873)
    at i._settlePromises (C:\Users\Shawn\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:207:22203)
    at i._drainQueue (C:\Users\Shawn\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:206:7831)
    at i._drainQueues (C:\Users\Shawn\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:206:7892)
    at Immediate.drainQueues (C:\Users\Shawn\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:206:5943)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

**Comment by elhay-av** [comment]
i get this to

node -v ➜ v7.0.0
npm -v ➜ 4.5.0
macOS sierra 10.12.4 (16E195)
