### ISSUE TITLE
How to use on remote linux server ?

### ISSUE THREAD

**Issue by hjgabrielsen** [q-nick/npm-gui#20]
Ii have npm-gui running on a remote server xxx.xxx.xxx.xxx , how do I configure it and access it  remotely?

**Comment by q-nick** [comment]
@hjgabrielsen  All you have to do is:

- `ssh` to your server on xxx.xxx.xxx.xxx
- navigate `cd` to folder where your app is located
- run `npm-gui` - it will bind to default port on xxx.xxx.xxx.xxx:1337 (this port must be available for incoming internet connections)
- on your PC open in browser `xxx.xxx.xxx.xxx:1337`

Be carefull when you allow connecting to `npm-gui`  on your remote server. That could be dangerous becouse there is no authentication and everybody could access it

**Comment by q-nick** [comment]
From README:

If you need to start server on another host, port, you should add host:port argument to command, example:

npm-gui localhost:9000


in your case it will be: `npm-gui xxx.xxx.xxx.xxx:1337`

**Comment by hjgabrielsen** [comment]
Tried all, 

events.js:182
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRNOTAVAIL xxx.xxx.xxx:1337
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at Server.setupListenHandle [as _listen2] (net.js:1305:19)
    at listenInCluster (net.js:1370:12)
    at doListen (net.js:1492:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:611:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
