### ISSUE TITLE
getting  Cannot set property 'latest' of undefined on windows

### ISSUE THREAD

**Issue by master96** [q-nick/npm-gui#22]
Hi, 
this modules works perfectly on linux. I shifted to windows to use more graphic softwares few days back.
Now when i am running npm-gui it is stuck with this error while loading page

`Unhandled rejection TypeError: Cannot set property 'latest' of undefined
    at C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:206:3480
    at i (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:1:888)
    at i._settlePromiseFromHandler (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:207:19369)
    at i._settlePromise (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:207:20172)
    at i._settlePromise0 (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:207:20873)
    at i._settlePromises (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:207:22203)
    at i._drainQueue (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:206:7831)
    at i._drainQueues (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:206:7892)
    at Immediate.drainQueues [as _onImmediate] (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:206:5943)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)

Unhandled rejection TypeError: Cannot set property 'latest' of undefined
    at C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:206:1773
    at i (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:1:888)
    at i._settlePromiseFromHandler (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:207:19369)
    at i._settlePromise (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:207:20172)
    at i._settlePromise0 (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:207:20873)
    at i._settlePromises (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:207:22203)
    at i._drainQueue (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:206:7831)
    at i._drainQueues (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:206:7892)
    at Immediate.drainQueues [as _onImmediate] (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:206:5943)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)

Unhandled rejection TypeError: Cannot set property 'latest' of undefined
    at C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:206:1773
    at i (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:1:888)
    at i._settlePromiseFromHandler (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:207:19369)
    at i._settlePromise (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:207:20172)
    at i._settlePromise0 (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:207:20873)
    at i._settlePromises (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:207:22203)
    at i._drainQueue (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:206:7831)
    at i._drainQueues (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:206:7892)
    at Immediate.drainQueues [as _onImmediate] (C:\Users\ajage\AppData\Roaming\npm\node_modules\npm-gui\npm-gui.js:206:5943)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)`

**Comment by aersamkull** [comment]
I get the same error

**Comment by q-nick** [comment]
Hi guys. 
I guess that problem is related with latest node version. I suggest you to switch to LTS Node, (currently 8.12.0)

I will consider to release newest version of npm-gui with few fixes.

**Comment by master96** [comment]
Tried 8.12.0 getting same error
