### ISSUE TITLE
npm-gui throws a JSON error in console when update a dependency

### ISSUE THREAD

**Issue by gorilla-leo** [q-nick/npm-gui#25]
OS: OSX High Sierra v. 10.13.6
npm v.6.4.1
node v. 10.9.0
Browser: Firefox Quantum 63.0.1

When I click on any update button of any dependency, the dependency is updated, but I got this error message in console:
```
Error: [object Object]                 pm-gui/dist/server/main.js:535:180028)
    at ChildProcess.s.on (/usr/local/liprocess/next_tick.js:68:7)
b/node_modules/npm-gui/dist/server/main -S" in "/Users/Enrique/Documents/projects/apollo-tutorial-kit2"
.js:535:167021)
    at ChildProcess.emit (events.js:182
:13)                                   1 -S" in "/Users/Enrique/Documents/projects/apollo-tutorial-kit2"
    at Process.ChildProcess._handle.one
xit (internal/child_process.js:237:12)
    at onErrorNT (internal/child_proces
s.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
executing: "npm install mysql2@1.6.4 -S" in "/Users/Enrique/Documents/projects/apollo-tutorial-kit2"

JSON error
executing: "npm install node-fetch@2.2.1 -S" in "/Users/Enrique/Documents/projects/apollo-tutorial-kit2"

JSON error
executing: "npm install sqlite3@4.0.3 -S" in "/Users/Enrique/Documents/projects/apollo-tutorial-kit2"

JSON error
executing: "npm install ajv@6.5.5 -S" in "/Users/Enrique/Documents/projects/apollo-tutorial-kit2"

JSON error
```

**Comment by q-nick** [comment]
@gorilla-leo 
Does this console error has some impact on `GUI` view, or your work? Do you see that something is not updating in your `package.json` or updating incorrectly?

I left all error logs in console for easier issue solving.
