### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by clabough** [q-nick/npm-gui#29]
npm-gui v1.0.7

\>npm-gui
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 127.0.0.1:1337
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1501:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)

**Comment by wiesmin138** [comment]
Try changing port.
It worked for me.

**Comment by darkred** [comment]
Manually killing the old `node.exe` process 
that was running `C:\Users\Kostas\AppData\Roaming\npm\\node_modules\npm-gui\index.js`
fixed the issue for me.
